#!/bin/sh
echo "Making symlinks for current user"
echo $PWD
ln -fs $PWD/.oh-my-zsh -t ~/
ln -fs $PWD/.zshrc -t ~/
ln -fs $PWD/.dircolors -t ~/

echo "Copying fonts to /usr/share/fonts/"
sudo cp fonts/* /usr/share/fonts/

echo "Making symlinks for root"
sudo ln -fs $PWD/.oh-my-zsh /root/
sudo ln -fs $PWD/.zshrc /root
sudo ln -fs $PWD/.dircolors /root/